server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://62.234.111.74/uchain?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8

jwt:
  secret: myscret
  expiration: 1296000
  tokenStart: "Bearer "
  tokenName: Authorization

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.uchain.jwtlogindemo.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
